name: Contribution checks

on:
  push:
    branches:
      - master
      - maint/*
  pull_request:
    branches:
      - master
      - maint/*

defaults:
  run:
    shell: bash

jobs:
  stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install black/isort
        run: python -m pip install black isort
      - name: Check fMRIPrep
        run: |
          python -m black --check fmriprep
          python -m isort --check fmriprep
      - name: Check wrapper
        run: |
          python -m black --check wrapper
          python -m isort --check wrapper
